# Model arguments
# model_name_or_path: alignment-handbook/zephyr-7b-sft-qlora
model_name_or_path: alignment-handbook/zephyr-7b-sft-full
# model_name_or_path: HuggingFaceH4/mistral-7b-sft-beta
torch_dtype: bfloat16
use_flash_attention_2: true

# LoRA arguments
#use_peft: true
#load_in_4bit: true
lora_r: 128
lora_alpha: 128
lora_dropout: 0.05
lora_target_modules:
- q_proj
- k_proj
- v_proj
- o_proj
- gate_proj
- up_proj
- down_proj

# Data training arguments
dataset_mixer:
  HuggingFaceH4/ultrafeedback_binarized: 1.0
dataset_splits:
- train_prefs
- test_prefs
preprocessing_num_workers: 12

# SimPOTrainer arguments
bf16: true
beta: 2.0
gamma: 1.6
do_eval: true
evaluation_strategy: steps
eval_steps: 2000
# eval_steps: 10
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: simpo-exps
learning_rate: 5.0e-6
# learning_rate: 3.0e-7
log_level: info
logging_steps: 100
lr_scheduler_type: cosine
max_length: 1024
max_prompt_length: 512
num_train_epochs: 1
optim: paged_adamw_32bit
output_dir: outputs/mistral-7b-base-simpo-qlora
run_name: mistral-7b-base-simpo-qlora
per_device_train_batch_size: 1
per_device_eval_batch_size: 2
push_to_hub: false
save_strategy: "epoch"
report_to:
- wandb
save_total_limit: 20
seed: 42
warmup_ratio: 0.1
