# Model arguments
model_name_or_path: alignment-handbook/zephyr-7b-sft-qlora
torch_dtype: null
use_flash_attention_2: false

# LoRA arguments
use_peft: true
load_in_4bit: true
lora_r: 128
lora_alpha: 128
lora_dropout: 0.05
lora_target_modules:
- q_proj
- k_proj
- v_proj
- o_proj
- gate_proj
- up_proj
- down_proj

# Data training arguments
dataset_mixer:
  HuggingFaceH4/ultrafeedback_binarized: 1.0
dataset_splits:
- train_prefs
- test_prefs
preprocessing_num_workers: 12

# SimPOTrainer arguments
bf16: false
beta: 2.0
gamma: 1.6
do_eval: true
evaluation_strategy: steps
eval_steps: 400
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: simpo-exps
learning_rate: 3.0e-7
log_level: info
logging_steps: 5
lr_scheduler_type: cosine
max_length: 512
max_prompt_length: 256
num_train_epochs: 1
optim: adamw_torch
output_dir: outputs/mistral-7b-base-simpo
run_name: mistral-7b-base-simpo
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
push_to_hub: false
save_strategy: "steps"
save_steps: 1000000
report_to:
- wandb
save_total_limit: 20
seed: 42
warmup_ratio: 0.1
